services:
  - type: web
    name: syncyomi
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    # Render attend que ton app écoute sur $PORT, donc on force Nginx sur 80
    envVars:
      - key: PORT
        value: 80
